version: "2.1"

services:
  nginx:
    restart: on-failure
    build: ./requirements/nginx
    image: nginx:test
    container_name: "nginx"
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
     - network

  mariadb:
    restart: on-failure
    env_file: 
      - .env
    build: ./requirements/mariadb
    image: mariadb:test
    container_name: "mariadb"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
     - network
  
  wordpress:
    restart: on-failure
    env_file: 
      - .env
    build: ./requirements/wordpress
    image: wordpress:latest
    container_name: "wordpress"
    volumes:
      - wordpress_data:/var/www/html
    depends_on: 
      mariadb:
        condition: service_healthy
    networks:
    - network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mj/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mj/data/wordpress
networks:
  network:
    driver: bridge