version: '3'

services:
  wordpress:
    restart: on-failure
    env_file: .env
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
#    networks:
#     - network

  db:
    restart: on-failure
    env_file: .env
    build: ./requirements/mariadb
    image: mariadb
    container_name: "mariadb"
    volumes:
      - mariadb_data:/var/lib/mysql
    #networks:
    #  - network

    # nginx:
    #   build: ./requirements/nginx
    #   image: nginx
    #   ports:
    #     - "443:443"
    #     - "8080:80"
    #   depends_on:
    #     - wordpress


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mj/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mj/data/wordpress

# networks:
#   network:
#     driver: bridge
